/**
 * Stats cross-table styles — shared between all stats tab components.
 * Extracted from the monolithic stats.tsx StyleSheet.
 */
import { StyleSheet } from 'react-native';
import theme from '@/constants/theme';

export const statsSharedStyles = StyleSheet.create({
  section: { marginBottom: 16 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 18, borderWidth: 1, borderColor: '#E8EDF2', shadowColor: '#0F172A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  heroCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, marginBottom: 20, ...theme.shadows.cardElevated, borderWidth: 1, borderColor: '#E8EDF2' },
  heroCardTablet: { padding: 28 },
  heroContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  heroStats: { gap: 18 },
  heroStatItem: { alignItems: 'center' },
  heroStatValue: { fontSize: 26, fontWeight: '800', color: theme.textPrimary, letterSpacing: -0.3 },
  heroStatLabel: { fontSize: 10, color: theme.textMuted, marginTop: 3, fontWeight: '600', textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  tabletRow: { flexDirection: 'row' as const, gap: 16, marginBottom: 0 },
  tabletHalf: { flex: 1 },
  sectionTabletWide: {},
  divider: { height: 1, backgroundColor: theme.border, marginVertical: 12 },
  // Format rows
  formatRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: theme.border },
  formatInfo: { width: 100 },
  formatName: { fontSize: 13, fontWeight: '600', color: theme.textPrimary },
  formatRecord: { fontSize: 10, color: theme.textMuted, marginTop: 2 },
  formatBarContainer: { flex: 1, marginLeft: 12 },
  // Score comparison
  scoreComparison: { flexDirection: 'row', alignItems: 'center', paddingBottom: 16 },
  scoreItem: { flex: 1, alignItems: 'center' },
  scoreValue: { fontSize: 34, fontWeight: '800', marginTop: 8, letterSpacing: -0.5 },
  scoreLabel: { fontSize: 10, color: theme.textMuted, marginTop: 4, fontWeight: '600', textTransform: 'uppercase' as const },
  scoreDiff: { alignItems: 'center', paddingHorizontal: 16 },
  scoreDiffBadge: { paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16, alignItems: 'center' },
  scoreDiffText: { fontSize: 22, fontWeight: '800', letterSpacing: -0.3 },
  scoreDiffLabel: { fontSize: 9, color: theme.textMuted, marginTop: 2, fontWeight: '600' },
  // Stats grid
  statsGrid3: { flexDirection: 'row', justifyContent: 'space-around' },
  gridItem: { alignItems: 'center' },
  gridValue: { fontSize: 30, fontWeight: '800', color: theme.textPrimary, letterSpacing: -0.5 },
  gridLabel: { fontSize: 10, color: theme.textMuted, marginTop: 4, fontWeight: '600', textTransform: 'uppercase' as const },
  // Mode win rates
  modeWinRates: { gap: 16 },
  modeWinRateItem: { gap: 8 },
  modeLabel: { fontSize: 13, fontWeight: '600', color: theme.textPrimary },
  // Duration
  durationHero: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  durationMain: { flex: 1, alignItems: 'center' },
  durationMainValue: { fontSize: 32, fontWeight: '700', color: theme.accent, marginTop: 4 },
  durationMainLabel: { fontSize: 12, color: theme.textMuted },
  durationMinMax: { flexDirection: 'row', gap: 16 },
  durationMinMaxItem: { alignItems: 'center' },
  durationMinMaxValue: { fontSize: 16, fontWeight: '600', color: theme.textPrimary, marginTop: 4 },
  durationMinMaxLabel: { fontSize: 10, color: theme.textMuted },
  totalTimeRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, gap: 10 },
  totalTimeLabel: { flex: 1, fontSize: 13, color: theme.textPrimary },
  totalTimeValue: { fontSize: 15, fontWeight: '700', color: theme.accent },
  // Cross table
  crossTableHeader: { flexDirection: 'row', alignItems: 'center', paddingBottom: 10, borderBottomWidth: 2, borderBottomColor: '#E2E8F0', marginBottom: 4 },
  crossTableHeaderLabel: { flex: 1.5, paddingLeft: 4 },
  crossTableHeaderText: { fontSize: 10, fontWeight: '800', color: theme.textSecondary, textTransform: 'uppercase', letterSpacing: 0.8 },
  crossTableHeaderCell: { flex: 1, alignItems: 'center', gap: 2 },
  crossTableHeaderCellText: { fontSize: 9, fontWeight: '700' },
  crossTableRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  crossTableRowAlt: { backgroundColor: '#F8FAFC' },
  crossTableRowLabel: { flex: 1.5, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 4 },
  crossTableRowLabelText: { fontSize: 12, fontWeight: '600', color: theme.textPrimary },
  crossTableCell: { flex: 1, alignItems: 'center' },
  crossTableCellValue: { fontSize: 15, fontWeight: '800', letterSpacing: -0.2 },
  crossTableCellPct: { fontSize: 9, color: theme.textMuted, marginTop: 1 },
  // Error styles
  errorHeroContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  errorHeroMain: { alignItems: 'center' },
  errorHeroValue: { fontSize: 52, fontWeight: '800', color: theme.error, marginTop: 8, letterSpacing: -1 },
  errorHeroLabel: { fontSize: 11, color: theme.textMuted, fontWeight: '600', textTransform: 'uppercase' as const },
  errorHeroBreakdown: { gap: 16 },
  errorHeroItem: { alignItems: 'center' },
  errorHeroItemValue: { fontSize: 20, fontWeight: '700', color: theme.textPrimary, marginTop: 4 },
  errorHeroItemLabel: { fontSize: 10, color: theme.textMuted },
  mostCommonError: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: theme.border },
  mostCommonErrorText: { flex: 1, fontSize: 12, color: theme.textSecondary },
  mostCommonErrorHighlight: { fontWeight: '700', color: theme.warning },
  errorRatesGrid: { flexDirection: 'row', gap: 12 },
  errorRatesGridTablet: { gap: 20 },
  errorRateCard: { flex: 1, alignItems: 'center', padding: 18, borderRadius: 18, borderWidth: 2, backgroundColor: '#FAFAFA' },
  errorRateValue: { fontSize: 32, fontWeight: '800', marginTop: 8, letterSpacing: -0.5 },
  errorRateLabel: { fontSize: 11, color: theme.textMuted, marginTop: 4, fontWeight: '600' },
  // Context comparison
  contextComparison: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingVertical: 8 },
  contextItem: { alignItems: 'center' },
  contextLabel: { fontSize: 12, color: theme.textMuted, marginBottom: 4 },
  contextValue: { fontSize: 32, fontWeight: '700' },
  contextSubLabel: { fontSize: 10, color: theme.textMuted },
  contextDivider: { paddingHorizontal: 16 },
  // Coaching tips
  coachingTip: { marginLeft: 38, marginRight: 8, marginBottom: 8, marginTop: -4, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: theme.tirColor + '08', borderRadius: 8, borderLeftWidth: 2, borderLeftColor: theme.tirColor + '40' },
  coachingTipHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 3 },
  coachingTipCause: { fontSize: 11, fontWeight: '600', color: theme.tirColor, fontStyle: 'italic' },
  coachingTipAdvice: { fontSize: 11, color: theme.textSecondary, lineHeight: 16 },
  coachingTipPoint: { marginLeft: 38, marginRight: 8, marginBottom: 8, marginTop: -4, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: theme.pointColor + '08', borderRadius: 8, borderLeftWidth: 2, borderLeftColor: theme.pointColor + '40' },
  // Error subsections
  errorSubsectionTitle: { fontSize: 12, fontWeight: '600', color: theme.textSecondary, marginTop: 8, marginBottom: 4 },
  consecutiveErrorsGrid: { flexDirection: 'row', justifyContent: 'space-around' },
  consecutiveErrorItem: { alignItems: 'center' },
  consecutiveErrorValue: { fontSize: 36, fontWeight: '700', color: theme.error },
  consecutiveErrorLabel: { fontSize: 11, color: theme.textMuted, textAlign: 'center', marginTop: 4 },
  // Boules comparison
  boulesCompChart: { marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: theme.border },
  boulesCompChartHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 },
  boulesCompChartTitle: { fontSize: 13, fontWeight: '700', color: '#D97706' },
  boulesCompMetricRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 14 },
  boulesCompMetricLabel: { width: 60, fontSize: 11, fontWeight: '600', color: theme.textSecondary, paddingTop: 2 },
  boulesCompBarsCol: { flex: 1, gap: 4 },
  boulesCompBarRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  boulesCompBarTrack: { flex: 1, height: 8, backgroundColor: theme.backgroundSecondary, borderRadius: 4, overflow: 'hidden' },
  boulesCompBarFill: { height: '100%', borderRadius: 4 },
  boulesCompBarValue: { fontSize: 11, fontWeight: '700', minWidth: 32, textAlign: 'right' as const },
  boulesCompLegend: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 4, justifyContent: 'center' as const },
  boulesCompLegendItem: { flexDirection: 'row', alignItems: 'center', gap: 5, maxWidth: 120 },
  boulesCompLegendDot: { width: 8, height: 8, borderRadius: 4 },
  boulesCompLegendText: { fontSize: 11, color: theme.textSecondary, fontWeight: '500' },
  // Precision workshop
  precisionWorkshopRow: { paddingVertical: 14 },
  precisionWorkshopHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  precisionWorkshopIcon: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  precisionWorkshopInfo: { flex: 1 },
  precisionWorkshopName: { fontSize: 13, fontWeight: '600', color: theme.textPrimary },
  precisionWorkshopMeta: { fontSize: 11, color: theme.textMuted, marginTop: 1 },
  precisionWorkshopStats: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 4 },
  precisionWorkshopStatItem: { alignItems: 'center' },
  precisionWorkshopStatValue: { fontSize: 18, fontWeight: '700', color: theme.textPrimary },
  precisionWorkshopStatLabel: { fontSize: 10, color: theme.textMuted, marginTop: 1 },
  precisionEvolutionRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10, marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: theme.border + '50' },
  precisionEvolutionLabel: { fontSize: 10, color: theme.textMuted, width: 50 },
  precisionEvolutionBars: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', gap: 4, height: 36 },
  precisionEvolutionBarCol: { flex: 1, alignItems: 'center' },
  precisionEvolutionBarTrack: { width: '100%', height: 28, backgroundColor: theme.backgroundSecondary, borderRadius: 3, overflow: 'hidden', justifyContent: 'flex-end' },
  precisionEvolutionBarFill: { width: '100%', borderRadius: 3 },
  precisionEvolutionBarLabel: { fontSize: 9, color: theme.textMuted, marginTop: 2 },
  // Insight (re-exported for direct use)
  insightBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 14, padding: 14, backgroundColor: '#FFFBEB', borderRadius: 14, borderLeftWidth: 3, borderLeftColor: '#F59E0B', borderWidth: 1, borderTopColor: '#FEF3C7', borderRightColor: '#FEF3C7', borderBottomColor: '#FEF3C7' },
  insightText: { flex: 1, fontSize: 12, color: '#78350F', lineHeight: 18 },
});
